Updates for Dictionaries Precourse lesson
Ada-Developers-Academy/ada-precourse-v2 pull request #110
Opened 2024-08-08 22:35 UTC by yangashley

Asana Task: https://app.asana.com/0/1205655776549324/1207935835560264/f

2024-08-08 22:38 UTC, yangashley commented on intro-to-python/dictionaries.md
> -        return None
We never go into detail about what try/except is in Precourse. It feels funny to throw this example in here without explaining the concept. 

Do you think we should remove it or leave a comment introducing it and let students explore their imagination? It does come up later in Unit 1.

Also, how do you feel about `return None` in the `else`? In the change I removed else, but can revert the change if you prefer it nested in there.

2024-08-08 22:38 UTC, yangashley commented on intro-to-python/dictionaries.md
> -
Same question as above ^^

2024-08-08 22:39 UTC, yangashley commented on intro-to-python/dictionaries.md
> +   1. Since we're using `snowman_dict` instead of `correct_guesses_list`, we can now remove the line of code `correct_guesses_list.append(user_input)`
I added more details because I felt like the change is a little complicated. What do you think?

2024-08-08 22:40 UTC, yangashley commented on intro-to-python/dictionaries.md
> -elif user_input_string in list1 or user_input_string in list2:
Somewhere along the line the variable names were changed to list1 and list2.... Changing them back to what we introduced them as in the Lists lesson.

2024-08-09 23:46 UTC, anselrognlie requested changes
Some of these, I could see us not wanting to tackle right now. If anything seems out of scope or needs more discussion, I'm happy to make some tickets.

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +    print("You have already guessed that letter")
Since `get_letter_from_user`hasn't been changed yet (so the param name hasn't changed) should we stick with `snowman_dict` rather than `word_dict` for this thought experiment?

I could also imagine `snowman_dict` could be confusing when they actually update the function, so keeping it as is is fine too.

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
Line 565:
```
The logical error comes in because all of the letters from the word are in the word_dict! If we only check to see if the letter is in the word_dict, we'll tell the user that they've already guessed a letter even if it's the first time they've guessed it if it's in the word! We need to add a check that looks at the value to see if it's `True` or `False`:
```
There are some places we can use "whether" and there's an awkward sentence (maybe `snowman_dict`?)
```
The logical error comes in because all of the letters from the word are already in `word_dict`, just with a `False` value! If we only check to see whether the letter is in `word_dict`, we'll tell the user that they've already guessed a letter even if it's the first time they've guessed it! We need to add a check that looks at the value to see whether it's `True` or `False`:
```

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +There is one important change to be aware of, right now we're just checking if the letter the user guessed is in the list of correct letters.  If we do that with the dictionary, we'll end up with a l
Also, a following paragraph that wasn't part of this change could use some fo the same changes (added as a file-level comment).

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>      print("You already guessed that letter")
mirrors a change a little further down
```suggestion
    print("You have already guessed that letter")
```

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +elif user_input_string in wrong_guesses_list or (user_input_string in word_dict and word_dict[user_input_string]):
potentially `snowman_dict` rather than `word_dict`.

But gosh this looks complicated without using `.get()` *(no change requested)*

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  * Check if the letter has been guessed or not
possible whether
```suggestion
* Check whether the letter has been guessed or not
```

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +    * If the value of "guessed" is `False` add `_` to the string
I'm sure we're avoiding a list and joining for simplicity, but this really hurts. 😭

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +## Write Some Code, Check the Code, Repeat
We need an explicit `<br />` between each pair of paragraphs so they don't get crushed together in the output.

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +As you're writing your implementation, be sure to call the helper function often so that you can see the output and confirm that it's working or not working. It's good practice to write a line or log
a "whether" for something that wasn't "if" 🙂  
```suggestion
As you're writing your implementation, be sure to call the helper function often so that you can see the output and confirm whether or not it's working. It's good practice to write a line or logical unit of code and then run it to check that you are getting the expected output before moving on to the next line of code. It is easier to identify where a bug is in one or two lines of code versus ten lines of code.
```

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +<summary>Here is our implementation.</summary>
Would it be too big to swap `elem_num` and `elem` to `letter_num` and `letter`?

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  Now that we have the helper function `generate_word_progress_string` working, let's revisit our original goal.  Right now we're returning the progress string, but what we really want to do is display
Possibly add `print_word_progress_string` and have it *call*`generate_word_progress_string` rather than renaming and changing the behavior (separation of concerns)?

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  The helper function `print_word_progress_string` provides a visual display of the players progress towards guessing the word. We also need to write a function that indicates whether or not all the le
typos
```suggestion
The helper function `print_word_progress_string` provides a visual display of the player's progress towards guessing the word. We also need to write a function that indicates whether or not all the letters of the word have been guessed. We will name this function `get_word_progress`. The function `get_word_progress` should return `True` if all the letters have been guessed, and `False` otherwise.
```

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  The helper function `print_word_progress_string` provides a visual display of the players progress towards guessing the word. We also need to write a function that indicates whether or not all the le
(I would also love this function to be called `is_word_guessed`.)

2024-08-09 23:46 UTC, anselrognlie commented on intro-to-python/dictionaries.md
Line 738:
```
1. The game prints out a section of the snowman drawing, showing one level for each incorrectly guessed letters
```
has a typo (letters/letter)
```
1. The game prints out a section of the snowman drawing, showing one level for each incorrectly guessed letter
```

2024-08-12 16:33 UTC, yangashley commented on intro-to-python/dictionaries.md
I updated the sentence to use "whether" but I don't get what you mean about the awkward sentence. Do you mean the variable `word_dict` should be `snowman_dict`?

2024-08-12 16:51 UTC, anselrognlie commented on intro-to-python/dictionaries.md
Sorry, it's hard to see the "awkward" bit wihtout the suggestion highlighting. There was a part that went
> even if it's the first time they've guessed it if it's in the word!
and I changed it to
> even if it's the first time they've guessed it!

The `snowman_dict` was a potential separate suggestion, but that should be made in consideration of whether it's overall more or less confusing to refer to the `word_dict` variable before we've talked about where it appears in the final updated code. Maybe we could add a little text earlier that makes it more clear that `word_dict` will be the updated parameter name or something like that. But I'm fine with leaving that, though I feel like some of the naming in our sample solution could use a revisit overall. (why was it ever OK that there was a `list1` and `list2`?)

2024-08-12 18:00 UTC, yangashley commented on intro-to-python/dictionaries.md
>  We could set up constants like:
Yeah I think this point would be best covered in another ticket for us to pick up at another time. Thank you!

I agree though. Before looking over this lesson for this ticket, I didn't know we covered homogenous vs heterogenous dictionaries and as the lesson is written it kind of feels like it's brought up just for the sake of mentioning it.

2024-08-12 20:25 UTC, yangashley commented on intro-to-python/dictionaries.md
> +<summary>Here is our implementation.</summary>
Yeah, I can do that. Noting here that I'll also be making the change in the code example (https://github.com/Ada-Developers-Academy/ada-precourse-v2/blob/main/intro-to-python/resources/src/dictionaries/games_dictionary.md) and also in snowman.py in replit.

2024-08-12 20:37 UTC, yangashley commented on intro-to-python/dictionaries.md
> +Let's look at some Python syntax related to dictionaries. The snippet below shows how we can create an empty dictionary, create a dictionary with key-value pairs in it, add a key-value pair to a dict
I'm thinking something like: 

```
### !callout-info

## Adding New Values to a Dictionary

Notice that we do not use a method to add a value to a dictionary in the example above. Unlike lists, which have an `append` method for adding new elements, dictionaries do not have a method for adding key-value pairs. Instead, dictionaries use square bracket notation to declare a new key and the assignment operator to assign a value. 

### !end-callout
```

How's that sound?

2024-08-12 21:39 UTC, yangashley commented on intro-to-python/dictionaries.md
> +    return None
I removed the second approach.

2024-08-12 22:06 UTC, yangashley commented on intro-to-python/dictionaries.md
> +2. Invoke `build_word_dict` and pass in `snowman_word` as an argument. We should use a variable called `snowman_dict` to capture the return value from calling the function.
Could we open another card to make this change? I know it's a small one here, but we'd need to make sure it's applied too the example code we link off to and also in the replit. 

I did it for the elem to letter_num suggestion, but I'm afraid of mucking it up even more and introducing some inconsistencies. 

I'd like to hold off on this one for now, get these changes merged in, check for continuity across all the lessons, and then make this change.

2024-08-12 22:21 UTC, yangashley commented on intro-to-python/dictionaries.md
>  The helper function `print_word_progress_string` provides a visual display of the players progress towards guessing the word. We also need to write a function that indicates whether or not all the le
We can add this rename from `get_word_progress` to `is_word_guessed` to the work to rename `snowman_dict` to `guessed_dict`?

2024-08-12 22:33 UTC, yangashley commented on intro-to-python/dictionaries.md
>  Now that we have the helper function `generate_word_progress_string` working, let's revisit our original goal.  Right now we're returning the progress string, but what we really want to do is display
This also has cascading changes: the code example, replit, snowman project directions (https://learn-2.galvanize.com/cohorts/2330/blocks/1151/content_files/intro-to-python/snowman.checkpoint.md?assessment=true). 

Hoping we can lump this change in with the name changes so that nothing falls through the cracks with this PR

2024-08-12 22:58 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  We could set up constants like:
Asana ticket: https://app.asana.com/0/1201700438643002/1208039033382219/f

2024-08-12 23:14 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  Now that we have the helper function `generate_word_progress_string` working, let's revisit our original goal.  Right now we're returning the progress string, but what we really want to do is display
Asana task: https://app.asana.com/0/1201700438643002/1208039036671787/f

2024-08-12 23:14 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  The helper function `print_word_progress_string` provides a visual display of the players progress towards guessing the word. We also need to write a function that indicates whether or not all the le
Asana task: https://app.asana.com/0/1201700438643002/1208039036671787/f

2024-08-12 23:15 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +2. Invoke `build_word_dict` and pass in `snowman_word` as an argument. We should use a variable called `snowman_dict` to capture the return value from calling the function.
Asana task: https://app.asana.com/0/1201700438643002/1208039036671787/f

2024-08-12 23:28 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  Now that we have the helper function `generate_word_progress_string` working, let's revisit our original goal.  Right now we're returning the progress string, but what we really want to do is display
Asana ticket: https://app.asana.com/0/1201700438643002/1208039036671787/f

2024-08-13 15:49 UTC, yangashley commented on intro-to-python/dictionaries.md
> +    print("You have already guessed that letter")
This suggestion can be addressed by: https://app.asana.com/0/1201700438643002/1208039036671787/f

2024-08-13 19:44 UTC, anselrognlie requested changes
A few more suggested edits. Sorry I misread some of the examples the first time through. 🙏

2024-08-13 19:44 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +2. Add additional feedback to the user when they attempt to guess a letter that they have already guessed that informs them if the letter is in the word or not.
avoids two that clauses (plus if/whether)
```suggestion
2. Add additional feedback to the user, when they attempt to guess a letter that they have already guessed, to inform them whether or not the letter is in the word.
```

2024-08-13 19:44 UTC, anselrognlie commented on intro-to-python/dictionaries.md
>  Now that we have the helper function `generate_word_progress_string` working, let's revisit our original goal.  Right now we're returning the progress string, but what we really want to do is display
Also need the enum → letter swap in the code excerpt for `print_word_progress_string` below here.

2024-08-13 19:44 UTC, anselrognlie commented on intro-to-python/resources/src/dictionaries/games_dictionary.md
> +    print(f"debug info: {snowman_word}")
Is uncommenting this intentional?

2024-08-13 21:42 UTC, yangashley commented on intro-to-python/dictionaries.md
> +    return None
Thanks, with the duplicate code cleaned up and with zip out of the picture, we're left with: 
```
def build_a_dictionary(keys, values):
    if len(keys) != len(values):
        return None
      
    result = {}
    for index in range(len(keys)):
        result[keys[index]] = values[index]
    return result
```

2024-08-13 21:46 UTC, yangashley commented on intro-to-python/resources/src/dictionaries/games_dictionary.md
> +    print(f"debug info: {snowman_word}")
In some places in Precourse it's not commented out and in other places it is so I've been going along and uncommenting it out for consistency.

2024-08-14 21:20 UTC, anselrognlie requested changes
I think we've almost got it! One small update, and one annoying suggestion. 😆

2024-08-14 21:20 UTC, anselrognlie commented on intro-to-python/dictionaries.md
line 447:
```
Two working implementations:
```
should be 
```
An example solution:
```
or something to that effect (singular)

2024-08-14 21:20 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +    return None
The suggestion ends up looking weird, but one more thought here is to fully lean in to the guard clause feel here, making the key access the main logic flow (less indented) over the None return.

I'm sure we'd prefer not messing around with this example any more, but I think I can say with confidence, this is how I would encourage folks to write it. However, this also requires rephrasing the hint, and possibly bringing back a second example if we'd want to contrast the affirmative and negative condition approach.

What do you think?

```suggestion
def get_value_from_dictionary(dict, key):
    if key not in dict:
        return None
        
    return dict[key]
```

2024-08-14 22:06 UTC, yangashley commented on intro-to-python/dictionaries.md
> +    return None
How about re-writing the hint like this:

```
##### !hint

A solution for this problem can be broken into the following steps:

1. Check to see if the dictionary does **not** contain the key
1. If the dictionary does not contain the key, return None
2. If the dictionary does contain the key, return the value associated with that key

<br/>

To check whether a key is in a dictionary, we can use the `in` operator.

```py
# True or False depending on whether some_key exists as a key in the dictionary some_dict
is_some_key_in_some_dict = some_key in some_dict
```

We can use the `not` operator with the `in` operator too. 
```py
# True or False depending on whether some_key does not exist as a key in the dictionary some_dict
is_some_key_in_some_dict = some_key not in some_dict
```

In general, the `in` operator checks whether some data is included in a data structure or string. For dictionaries, `in` checks whether a key is in a dictionary. If the key is present then the expression evaluates to `True` and if the key is absent then the expression evaluates to `False`.

##### !end-hint
```

And then re-writing the examples like this:
```
##### !explanation

Some example solutions:

```python

def get_value_from_dictionary(dict, key):
    if key not in dict:
        return None
	        
    return dict[key]
    
def get_value_from_dictionary(dict, key):
    if key in dict:
        return dict[key]

    return None
```

Both solutions work and are very similar! Pay close attention to the `if` statement and what is returned from each approach. We prefer the first solution because using the key to access a value from the dictionary and returning it is the main logic. This logic is **not** nested inside a conditional block and is less indented. 

While the second example works, it nests the logic of getting a value inside a conditional block and `return None` is emphasized as the main logic. Writing the code this way does not quite capture our intent to return some value from a dictionary.

##### !end-explanation
```

2024-08-15 00:36 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +    return None
That looks great! It sounds a little samey to the later one but I think that’s ok since this is a hint, so we can’t be sure that everyone will read them. Having each stand on its own feels like the right thing to do.

2024-08-15 19:09 UTC, anselrognlie approved these changes
Looks good! We just need a break between the paragraphs in the updated explanation.

2024-08-15 19:09 UTC, anselrognlie commented on intro-to-python/dictionaries.md
> +
Just needs a break
```suggestion

<br>

```

2024-08-15 19:16 UTC, merged