Python challenges
Ada-Developers-Academy/ada-precourse-v2 pull request #4
Opened 2021-01-04 01:34 UTC by CheezItMan

@jbieniosek Here are a couple of Python Challenges for Functions.  Let me know if this is what you had in mind, it's a good intro to making a python challenge.

2021-01-05 22:09 UTC, kaidamasaki commented on 00-preparing-for-ada/functions.md
> +        assert answer == False
If we just want to make sure something is falsey I'd recommend:

```suggestion
        assert not answer
```

If you want to make sure that they returned a literal `False` then I'd recommend:

```suggestion
        assert answer is False
```

2021-01-06 00:43 UTC, CheezItMan commented on 00-preparing-for-ada/functions.md
> +        original_input = mock.builtins.input
Updated, I'd tried that earlier, and failed for some reason and fell back on this style.  

Now the mocking works.  Enough sleep helps.

2021-01-06 17:03 UTC, jbieniosek requested changes

2021-01-06 17:03 UTC, jbieniosek commented on 00-preparing-for-ada/functions.md
> +def letter_in_snowman_word():
```suggestion
def snowman():
```

2021-01-06 17:03 UTC, jbieniosek commented on 00-preparing-for-ada/functions.md
> +            answer = p.letter_in_snowman_word()
```suggestion
            answer = p.snowman()
```

2021-01-06 17:03 UTC, jbieniosek commented on 00-preparing-for-ada/functions.md
> +            answer = p.letter_in_snowman_word()
```suggestion
            answer = p.snowman()
```

2021-01-06 17:03 UTC, jbieniosek commented on 00-preparing-for-ada/functions.md
> +            answer = p.letter_in_snowman_word()
```suggestion
            answer = p.snowman()
```

2021-01-06 17:03 UTC, jbieniosek commented on 00-preparing-for-ada/functions.md
> +            answer = p.letter_in_snowman_word()
```suggestion
            answer = p.snowman()
```

2021-01-06 17:03 UTC, jbieniosek commented on 00-preparing-for-ada/functions.md
> +* title: letter_in_snowman_word
```suggestion
* title: snowman
```

2021-01-06 17:20 UTC, CheezItMan commented on 00-preparing-for-ada/functions.md
> +def letter_in_snowman_word():
Great, I had been wondering if that was a helper function that the snowman app would be using.

2021-01-09 01:22 UTC, merged